### ISSUE TITLE
inline "?" breaks syntax highlight

### ISSUE THREAD

**Issue by orizens** [natewallace/angular2-inline#1]
hi.
I love this extension. 
This is the behaviour i'm getting when using "?" inline [UPDATED]: 
<img width="524" alt="screen shot 2016-11-10 at 5 29 38 pm" src="https://cloud.githubusercontent.com/assets/878660/20182686/4cc84cda-a76b-11e6-8ff1-93607efbd090.png">

Thanks.

**Comment by natewallace** [comment]
I'm using the built-in typescript grammar to render the values for attributes that have names that begin with a `[` or `(` character.  

I don't think the `?.` operator exists in the typescript or javascript languages which is why the syntax highlighting is messed up.  Are you using coffeescript?  You could use the typescript/javascript equivalent instead:

``` javascript
onSearch(query ? query.value : null)
```

**Comment by orizens** [comment]
sorry - i got confused and updated the screenshot.
according to [angular docs](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#expression-operators) "**?**" is a safe navigation operator that can be used in expressions.

**Comment by natewallace** [comment]
I see.  It doesn't seem worthwhile to re-create the typescript grammar just to support the `?.` operator in expressions.  

The other option would be not to use the typescript highlighting at all for expressions and instead have them colored the same as a plain text string.  I'm thinking there is value in having the expressions highlighted though so I'm not in love with that idea.

I don't think this is something I'm going to fix and will just recommend using the ternary operator instead.

**Comment by ValterSantosMatos** [comment]
@natewallace first thanks for the awesome extension, just to say its a bit sad since I use the elvis operator ("?") everywhere :( is there any way to apply a quick fix even if locally that would fix this?

**Comment by natewallace** [comment]
You can turn off the typescript syntax highlighter on your local copy easy enough.  You will need to do the following steps:
1. Find and open the template.ng.json file found in the angular2-inline extension folder.  On my windows machine this file is found here:  
   `C:\Users\nwallace\.vscode\extensions\natewallace.angular2-inline-0.0.14\syntaxes\template.ng.json`
2. Remove the 4 objects that have `"include": "source.ts"` in them.  Here is an example with one of the objects highlighted that needs to be removed: 
   https://github.com/natewallace/angular2-inline/blob/fb10033d0da9d6a47696ce9dd4529c0c81348149/syntaxes/template.ng.json#L151-L153
3. Save the changes and restart vscode and you will no longer have typescript syntax highlights.

**Comment by orizens** [comment]
@natewallace 
thanks for the support.

**Comment by vteivans** [comment]
I have the same issue with the question mark, anywhere after this `[style.display]="loading ? 'none' : ''"` the syntax highlight breaks for the whole file.

**Comment by natewallace** [comment]
If you add a semicolon to the end of your statement it should fix the highlighting.

**Comment by vteivans** [comment]
great @natewallace thanks

**Comment by natewallace** [comment]
I've published version 0.0.15 which adds support for the elvis operator in syntax highlights.

**Comment by orizens** [comment]
@natewallace thanks.
will check it out when vsc will prompt for an update

**Comment by orizens** [comment]
hi @natewallace 
I noticed that while working with the new latest version 0.0.15, code completion stops working properly. the suggestion box is not shown when typing a word that supposed to exist from an import. it happens in snippets as well.
I get this "loading..." box:
<img width="501" alt="screen shot 2016-11-16 at 3 58 21 pm" src="https://cloud.githubusercontent.com/assets/878660/20350019/ab548062-ac15-11e6-983d-2164587f4a03.png">

**Comment by natewallace** [comment]
Oops.  I've published version 0.0.16 which has a fix for this issue.  Thanks for reporting it.

**Comment by rudyhuynh** [comment]
I've just try version 0.0.17 and this issue is still there.
Here's my sample code:
<span [ngClass]="image.liked ? 'liked' : 'default'"></span>

**Comment by natewallace** [comment]
The syntax highlighter is failing because it expects a semi-colon(;) at the end of your statement:
```html
<span [ngClass]="image.liked ? 'liked' : 'default';">
```

**Comment by elhigu** [comment]
@natewallace  Awesome plugin <3 I also came across this Would it be hard to make ternary operator to work without ending semicolon workaround? 

For example is it possible for plugin to implicitly add ending semicolon to all expressions in template so that they will conform syntax highlighter requirements?

**Comment by elhigu** [comment]
With semicolon work around and latest angular2 I got an error:

```html
<discount [type]="isSubscription ? 'Subscription' : 'Purchase';">...

Error: Template parse errors:
Parser Error: Binding expression cannot contain chained expression at the end of the expression 
```

Using parenthesis did seem to work as an another workaround
```html
<discount [type]="(isSubscription ? 'Subscription' : 'Purchase')">...
```

**Comment by natewallace** [comment]
@elhigu I'm not able to reproduce the Template parse error you've described.  Can you make sure you don't still have the old language-vscode-javascript-angular2 extension installed.  This can cause problems if it's still installed.

I'll take a look but I don't know if I can easily modify the ternary operator rules.  I'm using a copy of the typescript language rules for the bound attributes with some additions to support a few angular2 specific features like the elvis(?.) operator.

**Comment by elhigu** [comment]
That parse error in angular2 initialization started coming when I updated from 2.4.1 to 2.4.3. Somewhere between those version angular2 started to verify that there are no multiple statements passed to binding expression and trailing semicolon triggered that check.

So the parse error doesn't have anything to do with angular2-inline vscode plugin, it is only the first proposed workaround that doesn't work anymore with latest angular.
